{{- if .Values.ingress.enabled -}}
  {{- $fullName := .Values.service.name -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else -}}
apiVersion: extensions/v1
  {{- end }}
kind: Ingress
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "authn-example.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.oauth.enabled }}
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email"
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
