- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Get the username running
  become: false
  local_action: command whoami
  register: username_on_the_host

- name: Add user to group
  become: true
  user:
    name: "{{username_on_the_host.stdout}}"
    groups: docker
    append: true

- name: Reset ssh connection
  meta: reset_connection

- name: Check docker installed
  ansible.builtin.command: which docker
  register: docker_path
  ignore_errors: true

- name: Download install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/docker_install
    mode: '0770'
  when: docker_path.stdout == ''

- name: Install docker
  ansible.builtin.command: /tmp/docker_install
  when: docker_path.stdout == ''

- name: Install python dependencies
  become: true
  apt:
    update_cache: yes
    state: latest
    name: python3-pip

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Added registry host to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '^(.*?){{registry_host}}$'
    line: "192.168.5.2 {{registry_host}}"
    state: present

- name: Added registry as insecure
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: Restart docker

- name: Flush handlers
  meta: flush_handlers
