# Default values for authn-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

oauth:
  enabled: true

image:
  repository: weather-service
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  name: weather-service
  port: 5000

ingress:
  enabled: true
  hosts:
    - host: weather-service.local
      paths:
        - /

resources: {}
